# Generated by Django 6.0.5 on 2026-07-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_created_by_conversation_is_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
