# Generated by Django 6.0.5 on 2026-06-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
