# Generated by Django 5.2.3 on 2026-05-04 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lesson_name', models.CharField(max_length=100)),
                ('professor_name', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('downloads_count', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
