# Generated by Django 5.2.3 on 2026-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_note_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
