# Generated by Django 6.0.5 on 2026-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_savednote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
