# Generated by Django 6.0.5 on 2026-05-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_field_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='level',
            field=models.CharField(blank=True, choices=[('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(blank=True, choices=[('handwritten', 'دستنویس'), ('typed', 'تایپی'), ('slide', 'اسلاید'), ('exam', 'نمونه سوال')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='university',
            field=models.CharField(blank=True, choices=[('tehran', 'دانشگاه تهران'), ('sharif', 'صنعتی شریف'), ('azad', 'آزاد'), ('pnu', 'پیام نور')], max_length=50, null=True),
        ),
    ]
