# Generated by Django 5.2.3 on 2026-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'لایک'), ('comment', 'کامنت'), ('comment_like', 'لایک کامنت')], max_length=20),
        ),
    ]
