# Generated by Django 6.0.5 on 2026-06-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_note_average_rating_noterating_delete_rating'),
        ('social', '0008_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='notes.tag'),
        ),
    ]
