# Generated by Django 6.0.5 on 2026-06-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_alter_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'لایک'), ('comment', 'کامنت'), ('comment_like', 'لایک کامنت'), ('new_answer', 'پاسخ جدید')], max_length=20),
        ),
    ]
