# Generated by Django 6.0.5 on 2026-06-30 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_created_by_conversation_is_group_and_more'),
        ('social', '0012_notification_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'لایک'), ('comment', 'کامنت'), ('comment_like', 'لایک کامنت'), ('new_answer', 'پاسخ جدید'), ('new_message', 'پیام جدید')], max_length=20),
        ),
    ]
