# Generated by Django 6.0.5 on 2026-07-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_alter_postmedia_options_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
